log:
  level: debug
  disable_sentry: true
db:
  url: "postgres://auction:auction@auction_db/auction?sslmode=disable"
horizon:
  signer: SAMJKTZVW5UOHCDK5INYJNORF2HRKYI72M5XSZCBYAHQHR34FFR4Z6G4
  endpoint: "http://traefik/"
listener:
  addr: :80
auction:
  payment_signer: "SAMJKTZVW5UOHCDK5INYJNORF2HRKYI72M5XSZCBYAHQHR34FFR4Z6G4"
  skip_sign_check: false
  tx_expiration_time: 1m
cop:
  endpoint: http://cop
  upstream: http://auction
  service_name: "auction-service"
  service_port: "80"
  service_prefix: "/integrations/auction"
fiat_integrations:
  data:
  - endpoint: http://stripe/integrations/stripe
    currency: USD
nft_svc:
  endpoint: http://nft-svc
ethbidder:
  checkpoint: 8882144
  rpc: "wss://rinkeby.infura.io/ws/v3/575232417faf4efaa8f1d204e1fcab28"
  contract_address: "0x746689a27507839a6BD71fd3678169D3B4a28893"
  eth_signer: "75603080DAED3924A5544F6815688A2E94F07C89864BFB750D99A8F107B8E3E8"
oracle:
  asset: "ethereum"
  quote: "usd"