rpc:
  endpoint: "wss://rinkeby.infura.io/ws/v3/0bab5f96a5e946b1a6403fd303526019"
  start_point: 8324100

horizon:
  endpoint: "http://traefik/"
  signer: "SAMJKTZVW5UOHCDK5INYJNORF2HRKYI72M5XSZCBYAHQHR34FFR4Z6G4"

listener:
  addr: :80

cop:
  endpoint: http://cop
  upstream: http://bridge
  service_name: bridge
  service_port: 80
  service_prefix: /integrations/bridge

bridger:
  owner: "GBA4EX43M25UPV4WIE6RRMQOFTWXZZRIPFAI5VPY6Z2ZVVXVWZ6NEOOB"
  signer: "SAMJKTZVW5UOHCDK5INYJNORF2HRKYI72M5XSZCBYAHQHR34FFR4Z6G4"
  contract_address: "0x8A6D4B2E3c7DA7bBAFCAC1e151279e2BA957b33a"

signer:
  eth_signer: "75603080DAED3924A5544F6815688A2E94F07C89864BFB750D99A8F107B8E3E8"

log:
  level: debug
  disable_sentry: true

nft_svc:
  endpoint: http://nft-svc