rpc:
  endpoint: "wss://rinkeby.infura.io/ws/v3/0bab5f96a5e946b1a6403fd303526019"
  start_point: 8762084

horizon:
  endpoint: "http://traefik/"
  signer: "SAMJKTZVW5UOHCDK5INYJNORF2HRKYI72M5XSZCBYAHQHR34FFR4Z6G4"

listener:
  addr: :80

cop:
  endpoint: http://cop
  upstream: http://bridge
  service_name: bridge
  service_port: 80
  service_prefix: /integrations/bridge

bridger:
  owner: "GBA4EX43M25UPV4WIE6RRMQOFTWXZZRIPFAI5VPY6Z2ZVVXVWZ6NEOOB"
  signer: "SAMJKTZVW5UOHCDK5INYJNORF2HRKYI72M5XSZCBYAHQHR34FFR4Z6G4"
  contract_address: "0x0FD00D4CC160dDEF9d21245fBaE1F68C669CD5E8"
  asset_address: "0x580Da36625bA6c5c3e40B511E84B276b2A668d04"

signer:
  eth_signer: "75603080DAED3924A5544F6815688A2E94F07C89864BFB750D99A8F107B8E3E8"

log:
  level: debug
  disable_sentry: true

nft_svc:
  endpoint: http://nft-svc