log:
  level: debug
  disable_sentry: true

db:
  url: "postgres://marketplace:marketplace@marketplace_db/marketplace?sslmode=disable"

horizon:
  signer: SAMJKTZVW5UOHCDK5INYJNORF2HRKYI72M5XSZCBYAHQHR34FFR4Z6G4
  endpoint: "http://traefik/"

listener:
  addr: :80

marketplace:
  payment_signer: "SAMJKTZVW5UOHCDK5INYJNORF2HRKYI72M5XSZCBYAHQHR34FFR4Z6G4"
  skip_sign_check: false
  tx_expiration_time: 1m
  prolongation_time: 15m

cop:
  endpoint: http://cop
  upstream: http://marketplace
  service_name: "marketplace-service"
  service_port: "80"
  service_prefix: "/integrations/marketplace"

coinpayments:
  merchant_id: "6936542314febfcc8dd3955fce88e0be"
  address: https://www.coinpayments.net/api.php
  private_key: "1eb579C1eae6c5CbB5743Bd2128BA688c5fa3d30989f5915c07bF701b489025a"
  public_key: "e38e33ba60ba1c95c709b492d7196ab1b2a657435e44410487f8333632220330"
  ipn_secret: "supersekr1tandsecure"
  request_timeout: 30

oracle:
  asset: "ethereum"
  quote: "usd"

coinpayer:
  checkpoint: 8882144
  rpc: "wss://rinkeby.infura.io/ws/v3/575232417faf4efaa8f1d204e1fcab28"
  contract_address: "0xFd624E993d54299F50C8F45aBedC2aac47828979"
  eth_signer: "75603080DAED3924A5544F6815688A2E94F07C89864BFB750D99A8F107B8E3E8"

4bill:
  url: https://api.4bill.io
  api_key: 'M~xcKKT"Wi7{~oCruo"L,j_|[I._zA.W'
  point: "339"
  debug: true

payer:
  private_payer: false
  payment_service_id: 2
  dl_account_id: 317
  dl_wallet_id: 476
  payments_asset: "USD"
  fixed_fee: 500 # kopiyky
  dynamic_fee: 0.0125 # %
  debug: true

nft_svc:
  endpoint: http://nft-svc

fiat_integrations:
  data:
  - endpoint: http://stripe/integrations/stripe
    currency: USD

discounter:
  enabled: true
  asset: "BOXX"
  discounts:
  - lower_limit: 10
    upper_limit: 100
    percent: 20